name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure Credentials
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.DEPLOYMENT_TOKEN }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:latest .

      # Push the Docker image to GHCR
      - name: Push Docker image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy to on-premises server
      - name: Deploy to on-premises host
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          script: |
            sh -c '
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.DEPLOYMENT_TOKEN }}
            docker pull ghcr.io/${{ github.repository }}:latest

            # Stop and remove any running container with the same name
            docker stop cronkite || true
            docker rm cronkite || true

            # Generate a UUID for awslogs-stream
            LOG_STREAM_UUID=$(uuidgen)

            # Run the new container
            docker run -d --name cronkite \
            -p ${{ secrets.HTTP_PORT }}:${{ secrets.HTTP_PORT }} \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }} \
            -e DB_CREDENTIALS="${{ secrets.DB_CREDENTIALS }}" \
            -e DB_DATABASE="${{ secrets.DB_DATABASE }}" \
            -e SERVICE_FQDN="${{ secrets.SERVICE_FQDN }}" \
            -e HTTP_PORT="${{ secrets.HTTP_PORT }}" \
            -e N8N_WEBHOOK="${{ secrets.N8N_WEBHOOK }}" \
            -e N8N_API_KEY="${{ secrets.N8N_API_KEY }}" \
            -e VALKEY_HOST="${{ secrets.VALKEY_HOST }}" \
            -e CONTAINERIZED=true \
            --restart=always \
            --log-driver=awslogs \
            --log-opt awslogs-region=${{ secrets.AWS_REGION }} \
            --log-opt awslogs-group=${{ vars.LOGS_GROUP }} \
            --log-opt awslogs-stream="$LOG_STREAM_UUID" \
            -v ~/.aws:/root/.aws:ro \
            ghcr.io/${{ github.repository }}:latest
            '
